import React from 'react';
import { createRoot } from 'react-dom/client';
import { logger } from '@samurais-app/components';
import { App } from './app';
import { pkg } from './config';
logger('name', pkg.name);
logger('version', pkg.version);
logger('env', pkg.env as any);
const root = createRoot(document.getElementById('app'));
root.render(<App />);